public class ArthimatticalCalculations {
    public void Addition(integer a,integer b){
        integer sum = a+b;
        System.debug(sum);

    }
    // Dort islem
    public void Subtraction(integer a,integer b){
        integer sub = a-b;
        System.debug(sub);

    }
    public void Multiplication(integer a,integer b,integer c){
        integer multp = (a)*(b)*(c);
        System.debug(multp);

}
}