public class checkdatatypes {
    public void MethodBoolean() {
        Boolean checkBoolean= true;
        system.debug(checkBoolean);
    }
    public void MethodInteger() {
        integer varfirst= 1;
        integer varsecond= 2;
        system.debug(varfirst);
        system.debug(varsecond);    
    }
    public void Stringmethod() {
        String varname= 'Name';
        String var2name= 'your name';
        system.debug(varname);
        system.debug(var2name); 

    }
}

